### PR TITLE
Makefile.openhrp3 (#49): Added patch to modify calculation of acceleration value, climit*torqueConst*gearRatio

### PR DESCRIPTION
**Pull request by orikuma**
pull request which is related to issue #49

### CODE REVIEW

**Comment by 130s** [comment]
@YoheiKakiuchi @k-okada Is this good to merge to include in v[3.1.6](https://github.com/start-jsk/openhrp3/issues/48) or should we wait for the next version?

**Comment by k-okada** [comment]
@orikuma did you send this patch to openhrp3 repository?

**Comment by YoheiKakiuchi** [comment]
Sorry, I have sent patch few minute ago.
https://openrtp.jp/redmine/issues/2162

**Comment by k-okada** [comment]
closing, if you need this PR, please reopen

**Pull request closed without merging**
